apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-b-app
  namespace: team-b
  labels:
    team: b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: team-b-app
  template:
    metadata:
      labels:
        app: team-b-app
        team: b
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        resources:
          requests:
            cpu: "50m"
            memory: "60Mi"
          limits:
            cpu: "100m"
            memory: "120Mi"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: team-b-service
  namespace: team-b
  labels:
    team: b
spec:
  selector:
    app: team-b-app
  ports:
  - port: 80
    targetPort: 80
