apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: multi-tenant-eks
  region: us-east-1
  version: "1.29"
availabilityZones: ["us-east-1a", "us-east-1b"]
iam:
  withOIDC: true
nodeGroups:
  - name: private-nodes
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: true
    volumeSize: 20
    minSize: 2
    maxSize: 3
    amiFamily: AmazonLinux2023
