apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-demo-cluster
  region: ap-south-1

vpc:
  nat:
    gateway: Disable

managedNodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3